<a href="https://colab.research.google.com/github/Mahi-Anol/pytorch/blob/main/pytorch_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch 

In [3]:
torch.__version__

'1.13.1+cu116'

In [4]:
scalar=torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector=torch.tensor([7,8,0])

In [9]:
vector

tensor([7, 8, 0])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([3])

In [12]:
vector2=torch.tensor([[1,2],[3,5]])

In [13]:
vector2.ndim

2

In [14]:
vector2.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
Anol=torch.rand(size=(3,4))

In [19]:
Anol , Anol.shape , Anol.ndim ,Anol.dtype

(tensor([[0.0799, 0.4711, 0.1808, 0.1689],
         [0.2275, 0.3681, 0.7069, 0.1379],
         [0.0931, 0.9409, 0.2107, 0.4312]]),
 torch.Size([3, 4]),
 2,
 torch.float32)

In [20]:
Anol2=torch.zeros(size=(4,5))
Anol3=torch.ones(size=(2,5))

In [21]:
Anol2 , Anol2.shape , Anol2.ndim ,Anol2.dtype


(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.Size([4, 5]),
 2,
 torch.float32)

In [22]:
Anol3 , Anol3.shape , Anol3.ndim ,Anol3.dtype

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.Size([2, 5]),
 2,
 torch.float32)

In [23]:
rng=torch.arange(1,100,4)

In [24]:
rng

tensor([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
        73, 77, 81, 85, 89, 93, 97])

In [25]:
rng2=torch.zeros_like(input=rng)

In [26]:
rng,rng2

(tensor([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
         73, 77, 81, 85, 89, 93, 97]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0]))

In [27]:
rng3=torch.eye(6)

In [28]:
rng3

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=int, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='cuda', # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

<ipython-input-29-f89c892dea35>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  float_32_tensor = torch.tensor([3.0, 6.0, 9.0],


(torch.Size([3]), torch.int64, device(type='cuda', index=0))

In [30]:

torch.cuda.is_available()

True

In [31]:
torch.cuda.device_count()

1

In [32]:
torch.cuda.current_device()

0

In [33]:
torch.cuda.get_device_name(0)

'Tesla T4'